export const questions = [
  "How are you feeling right now?",
  "Did anything specific happen today that influenced your mood?",
  "Have you felt stressed or overwhelmed today?",
  "Did someone’s actions positively or negatively affect your mood?",
  "Have you experienced any moments of joy or satisfaction today?",
  "Did you face any challenges or frustrations today?",
  "Were there any unexpected events that affected your mood?",
  "Did you get enough sleep last night?",
  "How much physical activity did you engage in today?",
  "Have you eaten balanced meals today?",
  "Did you spend time outdoors today?",
  "Have you talked to someone about your feelings today?",
  "Did you accomplish something that made you proud today?",
  "Were you able to relax and take breaks today?",
  "Did you feel appreciated by someone today?",
  "Was there something that made you anxious today?",
  "Did you listen to music or do something creative today?",
  "Have you practiced gratitude today?",
  "Did you help someone or receive help today?",
  "How has your energy level been throughout the day?",
  "Did you laugh or smile today?",
  "Did you meditate or practice mindfulness today?",
  "Did you drink enough water today?",
  "Have you been feeling socially connected or isolated today?",
  "Did you get enough sunlight exposure today?",
  "Have you set or achieved a goal today?",
  "Did you engage in a hobby or activity you enjoy?",
  "How did your work or studies go today?",
  "Did you feel overwhelmed by responsibilities today?",
  "Were you able to handle negative emotions effectively?",
  "Did you feel productive and focused today?",
  "How was your appetite today?",
  "Did you have any self-care moments today?",
  "Did you experience any physical pain or discomfort today?",
  "Have you felt hopeful about the future today?",
  "Did you spend quality time with family or friends today?",
  "Did you face any conflicts or disagreements today?",
  "Were you able to stick to a routine today?",
  "How did your morning start today?",
  "Did you read something interesting today?",
  "Did you feel confident in yourself today?",
  "Did you avoid distractions and stay focused?",
  "Did you learn something new today?",
  "Did you take any deep breaths or moments of relaxation today?",
  "Did you feel in control of your emotions today?",
  "How was your overall motivation today?",
  "Did you have any dreams last night that affected your mood?",
  "Did you feel overwhelmed by technology or social media today?",
  "Did you practice any acts of kindness today?",
  "Was there a moment today that made you feel grateful?",
];
